### ISSUE TITLE
App header not displaying image in IE

### ISSUE THREAD

**Issue by jeffvg** [pxblue/collapsible-appbar#12]
#### Bug or feature request?
Bug
#### What is the expected behavior?
Image to display in header
#### What is the current behavior?
No image and warning.
Warning: `NaN` is an invalid value for the `opacity` css style property.
    in div (at App.js:118)
    in div
    in Unknown (created by WithStyles(Toolbar))
    in WithStyles(Toolbar) (at App.js:109)
    in div (at App.js:108)
    in div (at App.js:88)
    in Unknown (created by WithStyles(App))
    in WithStyles(App) (at src/index.js:10)
    in Unknown (at src/index.js:9)
#### What are the steps to reproduce?
1. Run react collapsible app bar in IE

#### What is your environment?

 Framework
- [ ] Angular
- [X] React

 Browser
- [X] Internet Explorer
- [ ] Safari
- [ ] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [X] Windows
- [ ] Other
		
#### Anything else to add?
IE doesn't support the window.scrollY property

**Comment by joebochill** [comment]
We should be able to use scrollTop instead of scrollY
You can look in doc-it to see how we addressed this for the sticky scroll problem

**Comment by joebochill** [comment]
IE 11 does not support the background blend mode property for the blue filter effect on Abraham. I added a comment to reverse the order of the backgrounds on IE in order to see the image (unfiltered).

**Comment by joebochill** [comment]
#18 and #19 address the broken scrolling behavior, but the image blending is not fixable in IE.
